import Head from "next/head";
import {useRouter} from "next/router";
import styles from "@/styles/Home.module.css";
import {useEffect, useState} from "react";
import { Card } from '@/components/Card';
import { Character } from '@/interface';
import { GetStaticProps } from 'next';

export default function Product({item} : {item: Character}) {

  // const [items, setItems] = useState([])

	// const router = useRouter();

	// useEffect(() => {
	// 	fetch(`https://amiiboapi.com/api/amiibo/?name=${router.query.id}`)
	// 		.then((res) => res.json())
	// 		.then((data) => setItems(data.amiibo));
	// }, []);

	return (
		<>
			<Head>
				<title>Product</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
			{/* <main className={`${styles.main}`}> */}
        <h1>Product</h1>
        {/* {items.map((item, index) => ( */}
						<Card key={item.tail} item={item} />
					{/* ))} */}
				{/* </main> */}
				</div>
		</>
	);
}

//** Primero creamos los static paths
export const getStaticPaths = async () => {

	const character = await fetch("https://amiiboapi.com/api/amiibo/")
	const resp = await character.json();
	const data = resp.amiibo.slice(0, 50);
	const paths  = data.map((item: Character) => (
		{ params: { id: item.tail } }
	))

	return {
		paths: paths,
		fallback: true, 
	}
}

//** Segundo creamos el getStaticProps
export const getStaticProps: GetStaticProps = async ({ params }) => {

	const {id} = params as {id: string};

	const character = await fetch(`https://amiiboapi.com/api/amiibo/?tail=${id}`)
	const data = await character.json();

	return {
		props: {
			item: data.amiibo[0]
		},
	}
}
