import Head from "next/head";
import {useRouter} from "next/router";
import styles from "@/styles/Home.module.css";
import {useEffect, useState} from "react";
import { Card } from '@/components/Card';

export default function Product() {

  const [items, setItems] = useState([])

	const router = useRouter();

	useEffect(() => {
		fetch(`https://amiiboapi.com/api/amiibo/?name=${router.query.id}`)
			.then((res) => res.json())
			.then((data) => setItems(data.amiibo));
	}, []);

	return (
		<>
			<Head>
				<title>Product {router.query.id}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main}`}>
        <h1>Product</h1>
        {items.map((item, index) => (
						<Card key={index} item={item} />
					))}
			</main>
		</>
	);
}

